---
title: "自宅の温度と湿度"
author: "NosuZ"
date: "`r Sys.Date()`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(magrittr)
library(lubridate)
#library(stringr)
#library(openxlsx)
#library(readxl)
#library(writexl)
#library(qwraps2)
#library(janitor)
#library(kableExtra)
#library(ggthemes)
#library(ggsci)
# https://github.com/thomasp85/scico/issues/2
#library(scico)
# ggplot has default viridis
# https://ggplot2.tidyverse.org/reference/scale_viridis.html
##library(viridis)

#library(Epi) # 95% CI for chisq.test

##library(DBI)
#library(odbc)
library(googlesheets4)

#library(whisker) # Mustache syntax
#library(mondate)

#library(slider) # 移動平均
library(ggh4x) # dnorm line on ggplot

select <- dplyr::select

```

```{r}
#esp32 <- read_excel("~/Downloads/ESP32 気温と湿度.xlsx")

gs4_auth()
# ~/.Renviron
#esp32 <- read_sheet(Sys.getenv("ESP32_SHEET"))
config <- config::get(file=".config.yaml")
read_sheet(config$ESP32_SHEET, sheet = "env") %>% 
  # tzone = "JST" not worked.
  mutate(DATE_TIME = force_tz(DATE_TIME,tzone = "Asia/Tokyo")) -> esp32
#View(esp32)

esp32 %>% 
  pivot_longer(cols = c(ADT7410_TEMP, SHTC30_TEMP), names_to = "SENSOR", values_to = "TEMP") -> esp32_temp

```

## バッテリー電圧

```{r}
esp32 %>% 
  ggplot(aes(x=DATE_TIME, y=BATTERY_VOLT, color=DEV_ID)) +
  geom_point() + 
  #geom_line() +
  #scale_colour_viridis_d() + 
  #scale_color_viridis(discrete=TRUE) + 
  theme_light()
```

## 室温

```{r}
start_point <- now() - hours(36)
esp32_temp %>% 
  filter(DATE_TIME >= start_point) %>% 
  ggplot(aes(x=DATE_TIME, y=TEMP, color=SENSOR, shape=DEV_ID)) +
  geom_point() + 
  geom_line() +
  #scale_colour_viridis_d(option = "cividis") + 
  #scale_color_viridis(discrete=TRUE) + 
  theme_light()

esp32_temp %>% 
  ggplot(aes(x=DATE_TIME, y=TEMP, color=SENSOR, shape=DEV_ID)) +
  geom_point() + 
  geom_line() +
  #scale_colour_viridis_d(option = "cividis") + 
  #scale_color_viridis(discrete=TRUE) + 
  theme_light()

```

### 最低気温

```{r}
esp32_temp %>% 
  mutate(DATE = floor_date(DATE_TIME, unit="day")) %>% 
  group_by(DATE) %>% 
  slice(which.min(TEMP)) %>% 
  ggplot(aes(x=DATE, y=TEMP)) +
  geom_point() + 
  geom_line() +
  theme_light()

```

### 最高室温と最低室温

```{r}
esp32_temp %>% 
  mutate(DATE = floor_date(DATE_TIME, unit="day")) %>% 
  group_by(DATE) %>% 
  summarise(TEMP_MIN = min(TEMP), TEMP_MAX=max(TEMP)) %>% 
  ungroup() %>% 
  pivot_longer(cols = c(TEMP_MIN, TEMP_MAX), names_to = "MIN_MAX", values_to = "TEMP") %>% 
  ggplot(aes(x=DATE, y=TEMP, color=MIN_MAX)) +
  geom_point() + 
  geom_line() +
  #scale_colour_viridis_d(option = "cividis", direction = -1) + 
  theme_light()

```


### 温度の誤差

```{r}
esp32 %>%
  mutate(DELTA = ADT7410_TEMP - SHTC30_TEMP) -> errors

errors %>% 
  summarise(n = n(),
            mean = mean(DELTA),
            sd = sd(DELTA),
            median = median(DELTA))

errors %>% 
  ggplot(aes(x=DATE_TIME, y=DELTA, color=DEV_ID)) +
  geom_point() +
  theme_light()

errors %>% 
  ggplot(aes(x=DELTA, color=DEV_ID)) +
  geom_density() +
  #stat_theodensity(colour = "red") +
  theme_light()

```

## 湿度

```{r}
esp32 %>% 
  ggplot(aes(x=DATE_TIME, y=SHTC30_HUMI, color=DEV_ID)) +
  geom_point() + 
  geom_line() +
  #scale_colour_viridis_d() + 
  #scale_color_viridis(discrete=TRUE) + 
  theme_light()
```

## Boot count

```{r}
esp32 %>% 
  ggplot(aes(x=DATE_TIME, y=BOOT_COUNT, color=DEV_ID)) +
  geom_point() + 
  #scale_colour_viridis_d() + 
  #scale_color_viridis(discrete=TRUE) + 
  theme_light()
```

